FIXED inspect.getargspec() deprecated in python 3.11
jookies/jasmin pull request #1093
Opened 2022-11-25 14:53 UTC by BlackOrder

Jasmin keep crashing in python 3.11, had to rollback to v3.9 to be stable.

Fix # module 'inspect' has no attribute 'getargspec' 

### Description
Rolled back the image to v3.9 from 3.11 and added the lock cleaning logic from the other image.

### Checks

- [x] My pull request adheres to the code style of this project
- [x] All the tests have passed

2022-11-25 19:53 UTC, farirat requested changes
Thank you for this PR, please take a look to the comments below.

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi
> -FROM python:3-buster
The issue with inspect.getargspec() is already fixed in #1085 and will be released on next week, please rollback this change.

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi.alpine
> -FROM python:3-alpine
The issue with inspect.getargspec() is already fixed in #1085 and will be released on next week, please rollback this change.

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi
> -FROM python:3.10-buster
The issue with inspect.getargspec() is already fixed in #1085 and will be released on next week, please rollback this change.

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi.alpine
> -FROM python:3.10-alpine
The issue with inspect.getargspec() is already fixed in #1085 and will be released on next week, please rollback this change.

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi.alpine
> -FROM python:3.10-alpine
And it's better to keep same base image as other dockerfiles (python:3-alpine)

2022-11-25 19:53 UTC, farirat commented on docker/Dockerfile.restapi
> -FROM python:3.10-buster
And it's better to keep same base image as other dockerfiles (python:3-alpine)

2022-11-25 22:44 UTC, BlackOrder commented
Thanks @farirat, i reverted the changes to the python image. but will keep the lock cleaning change. thank you.

2022-11-27 07:39 UTC, farirat approved these changes

2022-11-28 08:08 UTC, merged

2022-12-08 14:41 UTC, WilfriedTIANI commented
Good morning all,

Please i face this issue on python 3.10.6
please how to get the working branch

2022-12-09 14:17 UTC, farirat commented
hello @WilfriedTIANI 
Releasing is in progress: https://github.com/jookies/jasmin/pull/1095